### ISSUE TITLE
Improve the resource format section

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-gsreport#11]
Improve the presentation of the report to allow the user to better navigate the available information:

- [x] remove the white column on the left and remove the gray line strip on the top
- [x] maintain the table view that we have now but with an additional capability. When the user click on the format link another table appears containing the list of the involved resources like [this](https://data.gov.uk/data/report/publisher-resources/cabinet-office). In that section the user can always filter by organization
- [x] since we added this extension we have a **not-specified** format in the main ckan facet:

![gs-report-2](https://user-images.githubusercontent.com/1280027/37533986-c513185e-2943-11e8-8de3-06bf993ea1e7.png)

that should be removed

**Comment by cezio** [comment]
> since we added this extension we have a not-specified format in the main ckan facet:

I use not-specified placeholder for datasets where one or more resources don't have format specified. It's indexed in solr, and uses faceted field. I can move this to separate field, which is not faceted, but then it will not be selectable as a regular facet. By default UI will show field name as `None`. I'm not sure if this can be overriden in reasonable way:


![image](https://user-images.githubusercontent.com/116021/37924073-12779828-3131-11e8-99a4-bfdd4df8fbdc.png)

**Comment by cezio** [comment]
> maintain the table view that we have now but with an additional capability. When the user click on the format link another table appears containing the list of the involved resources like this. In that section the user can always filter by organization

Do I understand this correctly? The workflow should be:
 * user opens main resources report view
 * main resources report lists formats and count
 * user can click resource format name, which will then open per-format report
 * per-format report should contain:
    * publisher
    * dataset
    * resource + description
    * format
    (other fields from resource/dataset if needed)

  * user can filter per-resource report by organization with drop down selection
  * should user be able to filter also by clicking on organization name? or should organization name redirect somewhere else?

**Comment by tdipisa** [comment]
@cezio,

**not-specified:** I assume thet you have explicitly created this for the gs-report purposes, right? Is it strictly necessary? If yes at least we need to have this localized in i18n files.

**resource report workflow:** Correct, remember that you have to use organization intead of publisher. Organization name should not be clickable, so no actions required.

**Comment by cezio** [comment]
> not-specified: I assume thet you have explicitly created this for the gs-report purposes, right? Is it strictly necessary? If yes at least we need to have this localized in i18n files.

Yes, this is needed to have datasets queried in solr properly (without modifying ckan's search code). But this value is in solr index only, it's not attached to datasets. I can add translation to it.

> resource report workflow: Correct, remember that you have to use organization intead of publisher. Organization name should not be clickable, so no actions required.

Ok. Thanks for clarification.

**Comment by cezio** [comment]
> not-specified: I assume thet you have explicitly created this for the gs-report purposes, right? Is it strictly necessary? If yes at least we need to have this localized in i18n files.

This actually may be harder to get. The thing is, value in ui is not from template, but is coming from facet. We can generate per-language versions though, and save it similar as we did in dcatapit (with field with lang suffix). The bad thing is, we'll generate values for all offered languages, and when translation is changed for the field, solr should be reindexed.

**Comment by cezio** [comment]
I'm not sure if we need 'notes' column. In BBC's report it looks like they have some package customizations (like published status, which seems to be something else from active), so it's useless for us, unless we want to have something else there.

![image](https://user-images.githubusercontent.com/116021/38014532-5e0b0354-3269-11e8-808b-2ec5fa1a288a.png)

@tdipisa could you review and tell which columns do we need exactly?

**Comment by tdipisa** [comment]
@cezio 

- Organization: OK
- Dataset: OK
- Notes: NO
- Resources: OK
- Description: OK but only if we can truncate the description text to a max number of chars
- Format: OK
- Created: OK

can we have a way to exclude the not-specified from the Facet and have this only in the report?

**Comment by cezio** [comment]
> can we have a way to exclude the not-specified from the Facet and have this only in the report?

You mean from value list? Yes, but in order to have empty value searchable, i'll have to add separate field to solr index. It should be searchable, but it will be shown in ui as in my previous comment: 

https://github.com/geosolutions-it/ckanext-gsreport/issues/11#issuecomment-376258691

I can try to make localized field,  as in https://github.com/geosolutions-it/ckanext-gsreport/issues/11#issuecomment-376699481

**Comment by tdipisa** [comment]
@cezio, you mean that adding a separate field to make searchable resources without format, this field automatically appears in the format facet too?

**Comment by cezio** [comment]
> @cezio, you mean that adding a separate field to make searchable resources without format, this field automatically appears in the format facet too?

No, it doesn't show in facets, but it should be searchable. The thing is, ui will show this as a facet label below search input box, but there will be invalid (`None`) label for facet field name. See attached screenshot.

**Comment by tdipisa** [comment]
@cezio for facet:

![facet.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5943f6b8abdc49001a6611c9/125516c66e82c728ace21e0d46ee95992696c1e5cdf9ad4cae58f3806b1c65262851f62e74d3b570ec122305565f4eaa405a0e17a8add839baa47e21d40854b088270a36d43703adbf881eba03b824894984b0b88e4bc0fa70.png)
