### ISSUE TITLE
Improve the licenses section

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-gsreport#12]
Improve the presentation of the report to allow the user to better navigate the available information:

- [x] remove the white column on the left and remove the gray line strip on the top
- [x] add a new first column containing the complete name of the license, now we have only the identifier: cc-zero is for example **Creative Commons CC0**
- [x] review the count:
cc-zero is 239 but should be 240
notspecified is 1 but its seems that we don't have [any of them](http://188.165.62.180/dataset?license_id=notspecified)

**Comment by cezio** [comment]
> review the count:
cc-zero is 239 but should be 240
notspecified is 1 but its seems that we don't have any of them

This was caused by counting also private datasets, which are not visible by default in search results. i added filtering out private datasets in licenses report.
