### ISSUE TITLE
Fill all translations files

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-gsreport#14]
i18n files should be properly filled: de, it, en

**Comment by cezio** [comment]
translations updated, https://github.com/cezio/ckanext-gsreport/tree/ui_improvements/ckanext/gsreport/i18n

**Comment by tdipisa** [comment]
@cezio some entries are still missing in .po files

**Comment by cezio** [comment]
could you give an example?

**Comment by tdipisa** [comment]
closed with #13
