### ISSUE TITLE
Problem exporting reports in CSV format

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-gsreport#15]
@cezio

There is an Internal Server Error while exporting some reports in CSV format.

**Steps to reproduce (first scenario):**

1 - go to the following URL: http://188.165.62.180/report/resources-format

2 - select a format

3 - try to export the report in CSV format (JSON works fine) 

**Steps to reproduce (second scenario):**

1 - go to the following URL: http://188.165.62.180/report/broken-links

2 - try to export the report in CSV format (JSON works fine)

**Comment by cezio** [comment]
The problem was that report table had nested structures, which couldn't be serialized to csv. Fix for this will flatten report row structures.
