### ISSUE TITLE
Report translations

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-gsreport#2]
i18n files should be provided at least for:
Italian
English
Deutch

**Comment by tdipisa** [comment]
.po files (for it and de) must be properly filled

**Comment by tdipisa** [comment]
please @cezio can you just update .mo file now and do a new PR for this?

**Comment by tdipisa** [comment]
@cezio, it seems that the related PR has some issues to solve in the travis build.

**Comment by cezio** [comment]
PR should be fixed, but i can't move it to review.
